### ISSUE TITLE
Keyerror while importing Ecoinvent db

### ISSUE THREAD

**Issue by lefterav** [LCA-ActivityBrowser/activity-browser#333] opened 2019-11-17 16:36 UTC
Importing the Ecoinvent DB via a login (download) doesn't seem to finish, and it gives the following error:

```
Traceback (most recent call last):
  File "/home/lefterav/tools/miniconda/envs/ab/lib/python3.6/site-packages/activity_browser/app/ui/wizards/db_import_wizard.py", line 668, in initializePage
    self.update_system_model_combobox(self.version_combobox.currentText())
  File "/home/lefterav/tools/miniconda/envs/ab/lib/python3.6/site-packages/activity_browser/app/ui/wizards/db_import_wizard.py", line 679, in update_system_model_combobox
    self.system_model_combobox.addItems(self.system_models[version])
KeyError: ''

Traceback (most recent call last):
  File "/home/lefterav/tools/miniconda/envs/ab/lib/python3.6/site-packages/activity_browser/app/ui/wizards/db_import_wizard.py", line 459, in run
    self.run_ecoinvent()
  File "/home/lefterav/tools/miniconda/envs/ab/lib/python3.6/site-packages/activity_browser/app/ui/wizards/db_import_wizard.py", line 470, in run_ecoinvent
    self.run_download()
  File "/home/lefterav/tools/miniconda/envs/ab/lib/python3.6/site-packages/activity_browser/app/ui/wizards/db_import_wizard.py", line 506, in run_download
    self.downloader.download()
  File "/home/lefterav/tools/miniconda/envs/ab/lib/python3.6/site-packages/eidl/core.py", line 139, in download
    file_content = self.session.get(url + self.db_dict[db_key], timeout=60).content
KeyError: ('', '')

```

**Comment by dgdekoning** [comment] 2019-11-17 16:46
Interesting, so during creation of the dropdown menu it looks like some incorrect information is being passed around. I wonder where the problem is coming from now.

**Comment by dgdekoning** [comment] 2019-11-17 16:50
Can you tell me if you're using the stable or the development build, and which version?

**Comment by lefterav** [comment] 2019-11-17 17:30
I just realized that I had logged in as a guest user, so download should not be allowed by that license. If this is the reason, the GUI doesn't display any relevant error, and the command-line error is not any informative either. 
I am using the stable version of AB. No version/system was displayed in the dropdown menus, so I proceeded without them.

**Comment by dgdekoning** [comment] 2019-11-17 17:48
That is something we'd not considered, I'll see if there is a good way of showing an error when using a non-authorized account.
Thanks for responding!

**Comment by dgdekoning** [comment] 2019-12-13 10:43
@lefterav, the newest development build of the activity browser contains a possible fix for this issue, can you see if it resolves the issue (or at least, gives a usable error message)?

**Comment by dgdekoning** [comment] 2020-07-22 14:45
Closing this because it seems to be resolved. Please don't hesitate to reopen if the issue still occurs @lefterav.

**Closed by dgdekoning** 2020-07-22 14:45 UTC
