### ISSUE TITLE
Suggested improvement: additional column for comments for individual technosphere and biosphere flows

### ISSUE THREAD

**Issue by CHarpprecht** [LCA-ActivityBrowser/activity-browser#706] opened 2022-02-03 09:58 UTC
Right now, an activity definition has only 1 comment (i.e. Description) field for the entire activity. 

In the BW excel import format, it is possible to also have comments for each technosphere and biosphere flow. These comments are very useful for providing some additional metadata (e.g. references, unit conversions etc.). However, after the import into the AB, the comments on the exchange level are lost, as the AB does not offer the possibilities to show them. Thereby, important metadata is lost and not accessible anymore. 

Would it be possible to import these comments to the AB into an additional column for exchanges? It could be helpful to add an additional box <<Show comments>> at the the top of the activity next to <<Show uncertainty>>, which allows to display the comments column for technosphere and biosphere exchanges within that activity.

**Comment by marc-vdm** [comment] 2022-02-07 10:45
This is a duplicate of #583, however, we somehow failed to comment on it back then.

Yes, this would be quite useful! Plans are in place to have this, just nobody to actually do it. As far as I remember, we actually store the information -and you should see it again on export of the database-. We just don't show it in AB currently.

I'll have a check how much work this is and perhaps do it.

**Closed** 2022-02-15 10:34 UTC

**Comment by marc-vdm** [comment] 2022-02-15 10:35
We now have the comments field in the dev release.

**Comment by CHarpprecht** [comment] 2022-03-21 20:22
Fantastic, thank you @marc-vdm  :)
