### ISSUE TITLE
Different result for default scenario than standard LCA

### ISSUE THREAD

**Issue by brandchristina** [LCA-ActivityBrowser/activity-browser#744] opened 2022-03-11 10:36 UTC
Hi there,

if I calculate a scenario LCA the result for the default scenario is significantly different than the result in the standard LCA (10,6 g CO2-Eq. vs. 14,0 g CO2-Eq.). This should not be the case and I don't know which is the correct result. I think this relates to issue #592.

![Standard LCA](https://user-images.githubusercontent.com/101396206/157848233-1460f0d4-02dd-4cf2-8ca6-019e1f5e0ac3.PNG)
![Scenario LCA](https://user-images.githubusercontent.com/101396206/157848255-690ad289-4b4b-4863-b5d1-c6823d251e2d.PNG)

My problem occurs in the stable and in the development version of the ab. I already updated bw and ab but it doesn't fix the problem.

**Comment by marc-vdm** [comment] 2022-03-16 10:32
Could you share the database `File`>`Export Database` (excel export) and the scenario file?

(and what to put into the calculation setup.)

That way we could replicate the problem.

**Comment by brandchristina** [comment] 2022-03-21 09:46
I hope with the following information you can replicate my problem.

This is my database file:
[CarboRegio_Hackschnitzel.xlsx](https://github.com/LCA-ActivityBrowser/activity-browser/files/8314413/CarboRegio_Hackschnitzel.xlsx)

This is my scenario table:
[scenario_table_Hackervarianten.xlsx](https://github.com/LCA-ActivityBrowser/activity-browser/files/8314415/scenario_table_Hackervarianten.xlsx)

And these are the two LCA Setups for the standard and the scenario LCA:
![LCA Setup Standard](https://user-images.githubusercontent.com/101396206/159236863-49817b56-d045-4b90-8f16-70e1d570de76.PNG)
![LCA Setup Scenario](https://user-images.githubusercontent.com/101396206/159236855-1239c29a-c6d0-40b1-85e4-86a1433f5514.PNG)

**Comment by marc-vdm** [comment] 2022-03-21 11:25
Thanks, I have both good and bad news, but it's mostly bad.
The good news is that you're not doing anything wrong. AB seems to be doing weird things here.
The bad news is that I don't understand yet what the problem is. This will require a lot more time to understand I'm afraid. Anyway, you sharing these files is really helpful for us to better understand the problem.

I'm suspecting that AB might be messing with the parameter values in the 'standard LCA' in a way that we can't easily see.
I saw that when setting both `Anteil_Anbauhacker` and `Anteil_LkwHacker` to 1 in a scenario, the result is very close to the 'standard' result.

Anyway, as a intermediate fix, I'd suggest to trust the `default` result over the standard one, as you're explicitly setting values your want that way.

**Comment by marc-vdm** [comment] 2022-03-31 11:46
Hi @brandchristina, I've been looking further into the issue and have to come back from my previous advice.

Something in the whole parameters code seems very broken to me when looking at results. It looks to me like the default column in a scenarios file will be ignored (but also not always?). And instead the parameters will be used as 'default' values (which I don't think is supposed to happen). 

Additionally, there is somehow a disconnect between the results of a `standard LCA` and the `default` column when using parameters.

My new advice is the following: 
Trust the standard LCA and the non-default scenarios. 
I'm afraid something is not right with the default column somehow.

I'm sorry for the inconvenience.

**Comment by brandchristina** [comment] 2022-04-01 09:59
Hi @marc-vdm thank you for taking the time looking at this issue. 
Since I am unfortunately not able to understand what is happening there, I have to trust you which of the results are the true values. Thanks very much for sharing your new advice!

**Comment by marc-vdm** [comment] 2023-09-14 14:28
Closing this as resolved in #1025

**Closed by marc-vdm** 2023-09-14 14:28 UTC
Labels: bug, help-needed, parameters
