### ISSUE TITLE
Installation fail due to pre-link script in bw2parameters

### ISSUE THREAD

**Issue by maxkoslowski** [LCA-ActivityBrowser/activity-browser#320] opened 2019-11-06 12:07 UTC
Hi,
having installed the Activity Browser on my laptop where it runs smoothly, I also wanted to install it on my desktop computer. However, an error is raised when executing the transaction in the terminal window.
It says: "_C:\ProgramData\Anaconda3\lib\site-packages\conda\core\link.py:1144: UserWarning: Package haasad::bw2parameters-0.5.2-py_0 uses a pre-link script.
[…]
LinkError: pre-link script failed for package haasad::bw2parameters-0.5.2-py_0
location of failed script: C:\ProgramData\Anaconda3\pkgs\bw2parameters-0.5.2-py_0\Scripts\.bw2parameters-pre-link.bat
[…]
stderr: The command ""C:\…\.conda\envs\ab\python.exe"" could not be found […]_"

I'd be very grateful for any suggestions on how to solve this issue.

**Comment by dgdekoning** [comment] 2019-11-06 12:19
Hello!

It looks like conda is pulling the `bw2parameters` package from the [`haasad`](https://anaconda.org/haasad/bw2parameters) channel, while it should be coming from the [`cmutel`](https://anaconda.org/cmutel/bw2parameters) channel. Can you show how you've configured your channels (`conda config --show channels`) and how you're installing the activity browser?

**Comment by maxkoslowski** [comment] 2019-11-06 12:25
The channels are in this order:
  - defaults
  - bsteubing
  - conda-forge
  - cmutel
  - haasad

As for the installation, I used what is written in the instruction, i.e.: conda create --yes --name ab --channel conda-forge activity-browser

**Comment by maxkoslowski** [comment] 2019-11-06 12:41
Ah, nevermind, I found the mistake.  For some reason I was following part of the instruction on cmutel's fork where the channel configuration does not cover four but only three channels (same for the cardosan fork btw). Due to the resulting differing order, the installation did not succeed. Sorry for bothering - should have had a closer look!

**Comment by dgdekoning** [comment] 2019-11-06 13:14
It's no problem, great that you've figured it out!

**Comment by dgdekoning** [comment] 2019-11-11 14:14
Closing this as it seems the issue is resolved, please open it again if it isn't.

**Closed by dgdekoning** 2019-11-11 14:14 UTC
