### ISSUE TITLE
Unable to complete adding database (trying using MacOS and Windows 10)

### ISSUE THREAD

**Issue by ckhrmn** [LCA-ActivityBrowser/activity-browser#500] opened 2021-01-13 18:50 UTC
Hello All,

I am new here. I have been trying to add the database but unsuccessful both in MacOS and Windows 10 with exactly same problem, shown as following:
---------
raise XLRDError(FILE_FORMAT_DESCRIPTIONS[file_format]+'; not supported')
xlrd.biffh.XLRDError: Excel xlsx file; not supported
---------
The database I am trying to add is the given one, i.e. biosphere flows and impact categories. The AB version I have installed is 2.4 "activity-browser>2.4".

Has anyone experience same issue? please advise how to solve it.

**Comment by dgdekoning** [comment] 2021-01-14 07:41
Yes, this is caused by `xlrd` version 2.0.0 and up.

you will have to run one more command in your environment to downgrade `xlrd` to 1.2.0

```bash
conda install xlrd==1.2.0
```

See [here](https://github.com/LCA-ActivityBrowser/activity-browser/pull/497) and [here](https://github.com/brightway-lca/brightway2-io/issues/86) for additional information.

At some point, brightway2 will be patched so it no longer uses xlrd to try and read .xlsx files.

**Comment by ckhrmn** [comment] 2021-01-18 19:22
Thank you! solved.

**Comment by dgdekoning** [comment] 2021-02-01 08:23
A [temporary fix for this problem](https://github.com/LCA-ActivityBrowser/activity-browser/pull/497) is now included in both the stable (2.6.3) and the development version (2021-01-12), so I am closing this.

**Closed by dgdekoning** 2021-02-01 08:23 UTC
