### ISSUE TITLE
Error upon fresh AB-dev install

### ISSUE THREAD

**Issue by bsteubing** [LCA-ActivityBrowser/activity-browser#342] opened 2019-12-06 22:19 UTC
I cannot start up the ab-dev as I get this error:
Traceback (most recent call last):
  File "C:/Users/bernoulli/surfdrive/Leiden/python/GitHub/LCA-ActivityBrowser/activity-browser/run-activity-browser.py", line 2, in <module>
    from activity_browser import run_activity_browser
  File "C:\Users\bernoulli\surfdrive\Leiden\python\GitHub\LCA-ActivityBrowser\activity-browser\activity_browser\__init__.py", line 6, in <module>
    from .app import Application, run_activity_browser
  File "C:\Users\bernoulli\surfdrive\Leiden\python\GitHub\LCA-ActivityBrowser\activity-browser\activity_browser\app\__init__.py", line 7, in <module>
    from .application import Application
  File "C:\Users\bernoulli\surfdrive\Leiden\python\GitHub\LCA-ActivityBrowser\activity-browser\activity_browser\app\application.py", line 2, in <module>
    from .controller import Controller
  File "C:\Users\bernoulli\surfdrive\Leiden\python\GitHub\LCA-ActivityBrowser\activity-browser\activity_browser\app\controller.py", line 12, in <module>
    from activity_browser.app.ui.wizards.db_import_wizard import (
  File "C:\Users\bernoulli\surfdrive\Leiden\python\GitHub\LCA-ActivityBrowser\activity-browser\activity_browser\app\ui\wizards\__init__.py", line 2, in <module>
    from .parameter_wizard import ParameterWizard
  File "C:\Users\bernoulli\surfdrive\Leiden\python\GitHub\LCA-ActivityBrowser\activity-browser\activity_browser\app\ui\wizards\parameter_wizard.py", line 6, in <module>
    from activity_browser.app.bwutils import commontasks as bc
  File "C:\Users\bernoulli\surfdrive\Leiden\python\GitHub\LCA-ActivityBrowser\activity-browser\activity_browser\app\bwutils\__init__.py", line 7, in <module>
    from .metadata import AB_metadata
  File "C:\Users\bernoulli\surfdrive\Leiden\python\GitHub\LCA-ActivityBrowser\activity-browser\activity_browser\app\bwutils\metadata.py", line 13, in <module>
    class MetaDataStore(QObject):
TypeError: 'Shiboken.ObjectType' object is not iterable

**Comment by dgdekoning** [comment] 2019-12-08 10:12
Hey, this is caused by conda itself, as it now prefers to use the newest python 3.8 when creating a new environment.

[PySide2 does not support Python 3.8](https://bugreports.qt.io/browse/PYSIDE-1140). 

A temporary fix for this would be to either force a version of python that is either 3.6 or 3.7 or to edit the readme to add a 'python=3.7'  bit to the create/install command.

**Comment by dgdekoning** [comment] 2019-12-10 15:23
Fixed for newer installations with https://github.com/LCA-ActivityBrowser/activity-browser/commit/48d82d3241c96d9ca5bc89600e8e5cb620f9081e.

Existing environments can be downgraded by running:
```bash
conda install -c conda-forge -c pascallesage activity-browser-dev==2019.12.10 python=3.7
```
After which the new restriction should avoid unexpected python version updates when running `conda update`

**Closed by dgdekoning** 2019-12-10 15:23 UTC
