### ISSUE TITLE
Error in Downloading Data from Ecoinvent

### ISSUE THREAD

**Issue by msuherma** [LCA-ActivityBrowser/activity-browser#670] opened 2021-10-21 14:19 UTC
As I import the database from Ecoinvent, I always get:
`~/Application Support/EcoInventDownLoader/cutoff38.7z' is corrupted, please remove and re-download it.`

I have removed the file(s) several time and tried to re-download it from ther. However, it keeps giving me the same outcome. In addition, I have also tried for other DB such as APOS, consequential, both online and from locally downloaded files, same result.

Anyone has a similar issue? Please advise.

------------
system: MacOS Catalina (10.15.7)
python3.8

**Comment by haasad** [comment] 2021-10-21 16:10
Hey @msuherma,

are you using the development version of the activity-browser? There was a fix released for your problem today, see the discussion in #649 

```
conda update activity-browser-dev
```
should do the trick.

Please let me know if it still doesn't work after updating.

**Comment by CHarpprecht** [comment] 2022-04-01 16:03
@StpdFox , this issue still persists in the normal release. Will this be fixed soon?

**Comment by haasad** [comment] 2022-04-01 16:17
@CHarpprecht What version of the stable release are you running? To my knowledge this should be fixed since quite some time now, unless there's some kind of regression or new issue.

Latest version is 2.6.9, you can check with `conda list activity-browser` in your environment:
```
conda list activity-browser
# packages in environment at /home/adrian/miniconda3/envs/abstable:
#
# Name                    Version                   Build  Channel
activity-browser          2.6.9                      py_0    bsteubing
```
If you're running an older version `conda update activity-browser` should fix it. Otherwise I'd be grateful if you can post the output of `conda list` and the operating system you're using, so I can try to debug it.

**Comment by CHarpprecht** [comment] 2022-04-07 07:43
Hi @haasad,

thank you for looking into this!

I am running ab version 2.6.9

The output of conda list is the following:

Name                    Version                   Build  Channel
activity-browser          2.6.9                      py_0    bsteubing
appdirs                   1.4.4              pyh9f0ad1d_0    conda-forge
arrow                     1.2.2              pyhd8ed1ab_0    conda-forge
asteval                   0.9.23             pyhd8ed1ab_0    conda-forge
astunparse                1.6.3              pyhd8ed1ab_0    conda-forge
beautifulsoup4            4.10.0             pyha770c72_0    conda-forge
brightway2                2.4.2                      py_4    cmutel
brotli                    1.0.9                h8ffe710_6    conda-forge
brotli-bin                1.0.9                h8ffe710_6    conda-forge
brotli-python             1.0.9            py39h415ef7b_6    conda-forge
brotlicffi                1.0.9.2          py39h415ef7b_1    conda-forge
brotlipy                  0.7.0           py39hb82d6ee_1003    conda-forge
bw2analyzer               0.10                       py_1    cmutel
bw2calc                   1.8.1                      py_2    cmutel
bw2data                   3.6.4                      py_0    cmutel
bw2io                     0.8.6                      py_1    cmutel
bw2parameters             0.7                        py_0    cmutel
bw_migrations             0.1                        py_0    cmutel
bzip2                     1.0.8                h8ffe710_4    conda-forge
ca-certificates           2021.10.8            h5b45459_0    conda-forge
certifi                   2021.10.8        py39hcbf5309_1    conda-forge
cffi                      1.15.0           py39h0878f49_0    conda-forge
charset-normalizer        2.0.12             pyhd8ed1ab_0    conda-forge
cryptography              36.0.2           py39h7bc7c5c_0    conda-forge
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
dill                      0.3.4              pyhd8ed1ab_0    conda-forge
docopt                    0.6.2                      py_1    conda-forge
eidl                      1.4.2                      py_0    bsteubing
eight                     1.0.0                      py_0    conda-forge
et_xmlfile                1.0.1                   py_1001    conda-forge
fasteners                 0.17.3             pyhd8ed1ab_0    conda-forge
fonttools                 4.31.2           py39hb82d6ee_0    conda-forge
freetype                  2.10.4               h546665d_1    conda-forge
future                    0.18.2           py39hcbf5309_4    conda-forge
icu                       69.1                 h0e60522_0    conda-forge
idna                      3.3                pyhd8ed1ab_0    conda-forge
importlib-metadata        4.11.3           py39hcbf5309_0    conda-forge
importlib_metadata        4.11.3               hd8ed1ab_0    conda-forge
intel-openmp              2022.0.0          h57928b3_3663    conda-forge
jbig                      2.1               h8d14728_2003    conda-forge
jpeg                      9e                   h8ffe710_0    conda-forge
kiwisolver                1.4.2            py39h2e07f2f_0    conda-forge
lcms2                     2.12                 h2a16943_0    conda-forge
lerc                      3.0                  h0e60522_0    conda-forge
libblas                   3.9.0              13_win64_mkl    conda-forge
libbrotlicommon           1.0.9                h8ffe710_6    conda-forge
libbrotlidec              1.0.9                h8ffe710_6    conda-forge
libbrotlienc              1.0.9                h8ffe710_6    conda-forge
libcblas                  3.9.0              13_win64_mkl    conda-forge
libclang                  13.0.1          default_h81446c8_0    conda-forge
libdeflate                1.10                 h8ffe710_0    conda-forge
libffi                    3.4.2                h8ffe710_5    conda-forge
libiconv                  1.16                 he774522_0    conda-forge
liblapack                 3.9.0              13_win64_mkl    conda-forge
libpng                    1.6.37               h1d00b33_2    conda-forge
libtiff                   4.3.0                hc4061b1_3    conda-forge
libwebp                   1.2.2                h57928b3_0    conda-forge
libwebp-base              1.2.2                h8ffe710_1    conda-forge
libxcb                    1.13              hcd874cb_1004    conda-forge
libxml2                   2.9.12               hf5bbc77_1    conda-forge
libxslt                   1.1.33               h65864e5_3    conda-forge
libzlib                   1.2.11            h8ffe710_1014    conda-forge
lxml                      4.8.0            py39hb82d6ee_1    conda-forge
lz4-c                     1.9.3                h8ffe710_1    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
matplotlib-base           3.5.1            py39h581301d_0    conda-forge
mkl                       2022.0.0           h0e2418a_796    conda-forge
mrio_common_metadata      0.1.1                      py_0    cmutel
msys2-conda-epoch         20160418                      1    conda-forge
multiprocess              0.70.12.2        py39hb82d6ee_2    conda-forge
multivolumefile           0.2.3              pyhd8ed1ab_0    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
networkx                  2.7.1              pyhd8ed1ab_1    conda-forge
numpy                     1.22.3           py39h6331f09_0    conda-forge
openjpeg                  2.4.0                hb211442_1    conda-forge
openpyxl                  3.0.9              pyhd8ed1ab_0    conda-forge
openssl                   1.1.1n               h8ffe710_0    conda-forge
packaging                 21.3               pyhd8ed1ab_0    conda-forge
pandas                    1.4.1            py39h2e25243_0    conda-forge
pathos                    0.2.8              pyhd8ed1ab_0    conda-forge
patsy                     0.5.2              pyhd8ed1ab_0    conda-forge
peewee                    3.14.10          py39h539719c_0    conda-forge
pillow                    9.0.1            py39ha53f419_2    conda-forge
pip                       22.0.4             pyhd8ed1ab_0    conda-forge
pox                       0.3.0              pyhd8ed1ab_0    conda-forge
ppft                      1.6.6.4            pyhd8ed1ab_0    conda-forge
presamples                0.2.3                h39e3cac_0    bsteubing
psutil                    5.9.0            py39hb82d6ee_0    conda-forge
pthread-stubs             0.4               hcd874cb_1001    conda-forge
py7zr                     0.18.3             pyhd8ed1ab_0    conda-forge
pybcj                     0.5.1            py39hb82d6ee_0    conda-forge
pybcpy                    0.0.17             pyhd8ed1ab_0    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pycryptodomex             3.14.1           py39hb82d6ee_0    conda-forge
pyopenssl                 22.0.0             pyhd8ed1ab_0    conda-forge
pypardiso                 0.4.0              pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.7              pyhd8ed1ab_0    conda-forge
pyppmd                    0.18.1           py39h415ef7b_0    conda-forge
pyprind                   2.11.2          py39hcbf5309_1002    conda-forge
pyside2                   5.13.2           py39hc084194_4    conda-forge
pysocks                   1.7.1            py39hcbf5309_4    conda-forge
python                    3.9.12          h9a09f29_1_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python_abi                3.9                      2_cp39    conda-forge
pytz                      2022.1             pyhd8ed1ab_0    conda-forge
pyzstd                    0.15.1           py39h46500c5_0    conda-forge
qt                        5.12.9               h556501e_6    conda-forge
requests                  2.27.1             pyhd8ed1ab_0    conda-forge
salib                     1.4.5              pyh6c4a22f_0    conda-forge
scipy                     1.8.0            py39hc0c34ad_1    conda-forge
seaborn                   0.11.2               hd8ed1ab_0    conda-forge
seaborn-base              0.11.2             pyhd8ed1ab_0    conda-forge
setuptools                61.2.0           py39hcbf5309_3    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
soupsieve                 2.3.1              pyhd8ed1ab_0    conda-forge
sqlite                    3.37.1               h8ffe710_0    conda-forge
stats_arrays              0.6.5                      py_2    cmutel
statsmodels               0.13.2           py39h5d4886f_0    conda-forge
tabulate                  0.8.9              pyhd8ed1ab_0    conda-forge
tbb                       2021.5.0             h2d74725_0    conda-forge
texttable                 1.6.4              pyhd8ed1ab_0    conda-forge
tk                        8.6.12               h8ffe710_0    conda-forge
typing_extensions         4.1.1              pyha770c72_0    conda-forge
tzdata                    2022a                h191b570_0    conda-forge
ucrt                      10.0.20348.0         h57928b3_0    conda-forge
unicodecsv                0.14.1                     py_1    conda-forge
unicodedata2              14.0.0           py39hb82d6ee_0    conda-forge
unidecode                 1.3.4              pyhd8ed1ab_0    conda-forge
urllib3                   1.26.9             pyhd8ed1ab_0    conda-forge
vc                        14.2                 hb210afc_6    conda-forge
voluptuous                0.12.2             pyhd8ed1ab_1    conda-forge
vs2015_runtime            14.29.30037          h902a5da_6    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
whoosh                    2.7.4            py39hcbf5309_5    conda-forge
win_inet_pton             1.1.0            py39hcbf5309_3    conda-forge
wrapt                     1.14.0           py39hb82d6ee_0    conda-forge
xlrd                      2.0.1              pyhd8ed1ab_3    conda-forge
xlsxwriter                3.0.3              pyhd8ed1ab_0    conda-forge
xorg-libxau               1.0.9                hcd874cb_0    conda-forge
xorg-libxdmcp             1.1.3                hcd874cb_0    conda-forge
xz                        5.2.5                h62dcd97_1    conda-forge
zipfile-deflate64         0.2.0            py39hb82d6ee_1    conda-forge
zipp                      3.7.0              pyhd8ed1ab_1    conda-forge
zlib                      1.2.11            h8ffe710_1014    conda-forge
zstd                      1.5.2                h6255e5f_0    conda-forge

My operating system is Windows 10 Enterprise version 20H2. 
By the way, a colleague of mine faces the same issue (also Windows 10). 

Thank you very much!

**Comment by haasad** [comment] 2022-04-07 09:16
@CHarpprecht I don't have access to my windows machine until next week, so can't test it myself right now. 

Your environment looks good from what I can tell.

Two things that you could check, which might cause this issue:
- in https://github.com/LCA-ActivityBrowser/activity-browser/issues/742#issuecomment-1067840122 it was mentioned that this error appeared because the user didn't have permissions to download that specific version of ecoinvent. Could you if you can access it manually via https://v38.ecoquery.ecoinvent.org with your credentials?
- can you have a look at the file itself and check the size etc, maybe open it with some other unarchive program if you have one installed. You should see the path to the file in the error message

**Comment by CHarpprecht** [comment] 2022-04-09 15:22
Hi @haasad ,
you are completely right, I am sorry! I used the wrong ecoinvent login details which do not have access to ecoinvent3.8. 
Thank you for the explanation!

Is there a way to add this hint to the user (i.e. to check the coverage of the used ecoinvent license) when this error occurs?

**Comment by marc-vdm** [comment] 2022-04-11 06:40
@haasad, would it be possible for eidl to detect this license problem and throw a spefic error for this (or can we avoid listing non-available ei in the dowloader in the first place?)? In that case we can give the user a popup when this occurs. I'm not sure what ecoinvent will or will-not tell you about this when a user logs in.

**Comment by haasad** [comment] 2022-04-23 07:50
@CHarpprecht @marc-vdm I opened #775 to try and look for a way to display a better error message, I'm closing this issue

**Closed by haasad** 2022-04-23 07:50 UTC

**Comment by CHarpprecht** [comment] 2022-05-02 12:07
Great, thank you very much!
