### ISSUE TITLE
Superstructure database with premise 1.6.9 does not work

### ISSUE THREAD

**Issue by avdoever** [LCA-ActivityBrowser/activity-browser#1043] opened 2023-09-21 14:34 UTC
### Issue

I made a superstructure database with premise 1.6.9, with ecoinvent 3.8 and the following scenarios: 
![image](https://github.com/LCA-ActivityBrowser/activity-browser/assets/88483582/6dce4b00-da64-4237-8348-5787c48728e2)
However, running a simple lca calculation of any given activity from the database gives me an AttributeError: "NoneType'object has no attribute 'empty'. 
Running a calculation without providing the scenario difference file does not give an error (but mostly empty results obviously).

**Comment by romainsacchi** [comment] 2023-09-21 14:42
Did you run `update_all()` ?

**Comment by avdoever** [comment] 2023-09-21 14:45
Yes.  and update_cars() and update_buses()

**Comment by romainsacchi** [comment] 2023-09-21 17:00
OK, I think, in the meantime I release a fix, you can delete the "from key" and "to key" info from teh scenario difference file.

**Comment by marc-vdm** [comment] 2023-09-22 10:08
@avdoever Please close this if it's resolved :)

**Comment by avdoever** [comment] 2023-09-22 11:29
Removing the from key and to key  info did not work (the ab finds duplicates and cannot handle them). I will wait for the new release.

**Comment by marc-vdm** [comment] 2023-09-22 11:37
@avdoever What version of AB are you using? Since `2.9.0` we have updated the scenario loading with better feedback, However, I seem to recall we had no problems with duplicates before `2.9.0`, could you let me know what version you're using?

**Comment by avdoever** [comment] 2023-09-22 11:38
2.7.4

**Comment by tpsarblaster** [comment] 2023-10-09 07:04
@marc-vdm @romainsacchi Could you elaborate on the updates to SDFs? I'm using AB `2.9.0` and premise `1.7.1`, in which premise generates SDFs without keys by default. However, I'm having the same issue described above, where the AB interprets the lack of keys as a long list of duplicates. What am I missing?

Sidenote: SDFs did not generate at all for me with more recent versions of premise (`1.7.4` and `1.7.5`), but that's a discussion for another forum.

**Comment by marc-vdm** [comment] 2023-10-09 07:19
@Zoophobus Tagging you as well

**Comment by romainsacchi** [comment] 2023-10-09 07:53
I know this is not ideal, but the current behavior of `premise` is to not fill in the from and to keys, and let AB figure them out.

**Comment by romainsacchi** [comment] 2023-10-09 07:53
I know this is not ideal, but the current behavior of `premise` is to not fill in the from and to keys, and let AB figure them out.

**Comment by romainsacchi** [comment] 2023-10-09 07:59
@tpsarblaster regarding the issue with `premise` and superstructure databases, I'm on it and will get back with a fix soon.

**Comment by Zoophobus** [comment] 2023-10-09 08:08
thanks @romainsacchi, is there anything we can do to help?

**Comment by romainsacchi** [comment] 2023-10-09 08:16
@tpsarblaster  nope. `v.1.7.6` should be out in a few minutes and that should fix it. Let me know if it does not.

**Comment by tpsarblaster** [comment] 2023-10-09 08:22
@Zoophobus the exchanges in the superstructure file and database align. However, the AB is unable to find the key for any of them (the detailed view of duplicates lists every index from 0 to 65519 -- there are more in the SDF, but I guess it gives up after a while). The functionality to find keys based on other data seems to be missing for me, as when I remove the keys from a SDF with just one flow, instead of duplicates it gives the error: "Cannot run analysis without data."

The environment was created yesterday, using `conda create -n ab activity-browser`. However, I later installed the ScenarioLink plugin into the same environment -- could that be a possible source of the error? I am trying again in an environment without ScenarioLink and will update this comment with my findings.

**Comment by romainsacchi** [comment] 2023-10-09 08:27
@tpsarblaster @Zoophobus `ab-plugin-scenairolink` should notbe the issue, as it does not require a specific version of `activity-browser`. But try and let us know.

**Comment by tpsarblaster** [comment] 2023-10-09 09:25
@romainsacchi thanks, with `v.1.7.6`, SDFs are generated as intended. Now just to figure out how to use them :)

**Comment by marc-vdm** [comment] 2023-10-12 07:37
Hi @tpsarblaster, 

I'm not sure your issue was resolved by updating Premise. I will close this issue for now. 
If the scenario loading is still broken for you, please [open an new bug report](https://github.com/LCA-ActivityBrowser/activity-browser/issues/new?assignees=&labels=bug&projects=&template=bug_report.yml).

**Closed by marc-vdm** 2023-10-12 07:37 UTC

**Comment by tpsarblaster** [comment] 2023-10-12 09:23
Hi @marc-vdm, the issue is not resolved. Generating a superstructure database with premise "as intended" currently means that the scenario file is generated without the `key` variables -- which AB is not able to resolve for me. I've opened it as a bug report [here](https://github.com/LCA-ActivityBrowser/activity-browser/issues/1062).
