### ISSUE TITLE
Error #15: Initializing libiomp5md.dll, but found libiomp5md.dll already initialized.

### ISSUE THREAD

**Issue by mert21433** [LCA-ActivityBrowser/activity-browser#824] opened 2022-08-15 14:28 UTC
Hello!

Any ideas why this could be happening? I have another environment, could that be the reason?
Error text is here:

"OMP: Hint This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For more information, please see http://www.intel.com/software/products/support/."

**Comment by marc-vdm** [comment] 2022-08-16 07:20
This is a duplicate of #682. See that thread for the fix.

**Closed by marc-vdm** 2022-08-16 07:21 UTC

**Comment by shirubana** [comment] 2022-09-26 12:49
Adding a follow up option to solve this issue:

What I ended up doing instead of deleting the .dll was installing and reinstalling numpy (not sure if it matters but I did it twice, following a stackoverflow)[https://stackoverflow.com/questions/64209238/error-15-initializing-libiomp5md-dll-but-found-libiomp5md-dll-already-initial]. Why it works? Who knows.](this stackoverflow). Why it works? Who knows but it's less scary than deletting .dlls.

-- Also, if you choose to ignore the comment from the error itself,  the stackoverflowers recommend you can add this to the code somewhere:
import os
os.environ['KMP_DUPLICATE_LIB_OK']='True'
