### ISSUE TITLE
AB inherits GNU GPL3, perhaps too restrictive

### ISSUE THREAD

**Issue by PascalLesage** [LCA-ActivityBrowser/activity-browser#184] opened 2018-09-07 13:59 UTC
The AB uses Riverbank’s PyQt5, that has a GNU General Public License version 3.
AB therefore "inherits" the same licence. 
This makes it too restrictive for use in some commercial projects. 
@cmutel mentions that one possible solution would be to use the official bindings (https://www.qt.io/qt-for-python) which are not GPL.
The porting may be simple (e.g. https://github.com/OpenShot/openshot-qt/issues/1875).

**Comment by bsteubing** [comment] 2018-09-07 14:59
Thanks for pointing this out. A couple of years back we decided on Riverbank's PyQt over PySide. In the meantime it seems like the "Qt for Python" project (or PySide2) that is officially supported by Qt could become the state-of-the-art Qt library for Python. This is something that we will keep an eye on!

Regarding a commercial use: PySide2 offers the GNU Lesser General Public License (LGPL) or the Qt Commercial License (https://doc.qt.io/qtforpython/licenses.html). The LGPL is indeed less restrictive than the current GPL in the sense that the AB could be used in commercial software as long as the Qt part of the code remains open source. 

**Feel free to add your opinion here on whether the AB should (in the mid-term) switch to PySide2/LGPL in order to enable the use within commercial software.** 

Final note: for both PyQt5 and PySide2 there are commercial licenses, so technically, the current AB implementation could already be used in commercial applications if someone buys these licenses (disclaimer: not sure if this is 100% correct, I am not a lawyer...)

**Comment by PascalLesage** [comment] 2018-09-07 15:04
Thanks. 

Concerning your final note:

> for both PyQt5 and PySide2 there are commercial licenses, so technically, the current AB implementation could already be used in commercial applications if someone buys these licenses 

I'm not a lawyer either, but I have the impression that this would not directly solve the issue (it changes the licence of the upstream PyQt5, not that of the AB). One colleague is of the impression that an alternative AB licence would need to be available for users that have the commercial PyQt5 licence.

**Comment by haasad** [comment] 2018-09-14 16:42
First some technical input:
- Surprisingly enough the AB "runs" with PySide2 with just a few syntax changes: see this PR #188
- You can check it out yourself by setting up a conda following these steps (only tested on linux):
```
conda create -n pyside2_test python=3.6 -y
conda activate pyside2_test
conda install activity-browser-dev --only-deps -y
conda remove --force matplotlib -y
conda remove qt -y
pip install matplotlib
pip install pyside2
python run-activity-browser.py
```
- There are still some errors related to "method signatures", but I think this could be solved without a huge effort. Example:
```
TypeError: 'PySide2.QtWidgets.QComboBox.insertItems' called with wrong argument types:
  PySide2.QtWidgets.QComboBox.insertItems(int, dict_keys)
Supported signatures:
  PySide2.QtWidgets.QComboBox.insertItems(int, QStringList)
```

Just looking at the AB codebase, I would say that a switch to PySide2 is totally feasible. Installation and packaging is however a whole other beast, as is already evident from the convoluted environment setup above. Looking back, this has taken a lot of effort to make the AB easily accessible via conda: #16, #51, #128, #147, https://github.com/haasad/conda-pyqt-osx. Conda-forge currently only provides pyside2 5.6.0 with `QtWebKitWidgets` which doesn't work for the AB. Only solution that I see here at the moment is to package pyside2 5.11 with conda for all three major OS ourselves. This is a lot of work and not even guaranteed that I can make it work at all.

**Comment by haasad** [comment] 2018-09-14 16:58
Regarding the licensing issue, I personally don't have a strong preference as long as the AB stays open source and we can reach as many people as possible (which would probably favour LGPL).

> I'm not a lawyer either, but I have the impression that this would not directly solve the issue (it changes the licence of the upstream PyQt5, not that of the AB).

I agree on this. As far as I understand, we would need a dual-licensing setup like PyQt, otherwise a commercial PyQt-license doesn't change anything for the AB.

**Comment by PascalLesage** [comment] 2018-09-14 17:58
> I agree on this. As far as I understand, we would need a dual-licensing setup like PyQt, otherwise a commercial PyQt-license doesn't change anything for the AB.

This would absolutely be an easy and appreciated  solution. I would assume that the people who would need a less restrictive licence are those who are working on a project with revenues, and so paying the 500$ licence would not be a problem.

**Comment by dgdekoning** [comment] 2019-08-28 07:03
I've noticed recently that the `conda-forge` pyside2 package has been updated to 5.12.4. Meaning that it has become a bit easier to switch over from pyqt to pyside.
One thing I did note installing this newer version is that it brings in two quite hefty dependencies (clangdev and libclang),

**Comment by dgdekoning** [comment] 2019-09-10 12:21
Some more information:

- PySide2 [drops the use of `QVariant`](https://doc.qt.io/qtforpython/pysideapi2.html#qvariant). Which will have an effect on feeding special objects into and extracting out of `QAbstractItemModel` subclasses.
- The `defaults` channel `matplotlib` [package](https://anaconda.org/anaconda/matplotlib) has a dependency on `pyqt`. Switching to PySide2 requires that the activity browser and all its dependencies would need to use `https://anaconda.org/conda-forge/matplotlib-base` [from conda-forge](https://anaconda.org/conda-forge/matplotlib-base) instead to avoid collisions.
  - [Pull-request](https://github.com/conda-forge/matplotlib-feedstock/pull/178) which allowed the conda-forge package to split.
  - Currently, the only dependency which uses `matplotlib` is [`bw2analyzer`](https://github.com/cmutel/conda-recipes/blob/master/bw2analyzer/meta.yaml), which looks like a simple fix?
- The [comment](https://github.com/LCA-ActivityBrowser/activity-browser/issues/184#issuecomment-421416590) by @haasad is still true, only a minimal amount of refactoring is needed to get the AB running, though I did notice some tables rendering oddly.

**Comment by e4BdSBmUzHowFico5Ktn** [comment] 2019-10-01 08:36
As we've found here (Issue #288), using PyQt could be a source of trouble for (at least one, perhaps more) linux distros. 

If this is indeed a problem for multiple distros, the potential reach of AB could be limited by PyQt.

This together with the fact that it might not be too much trouble to switch to PySide2 (with its licensing advantages) could be a reason to switch over. 
Personally, I`m all for the least restrictive licensing possible.

Would it be possible for someone with some time available to run some VM's with different (popular) distros to see if #288 is a common problem?

I'd be happy to help refactoring/editing once/if I've got some more time available, although it's been quite a while I`ve worked on AB.

**Comment by dgdekoning** [comment] 2019-10-28 13:33
For people interested in trying a PySide2 implementation, please see [my refactoring branch](https://github.com/dgdekoning/activity-browser/tree/refactor-pyside2).

A working conda environment for this branch can be installed with: 
```bash
conda install -y -c conda-forge -c cmutel -c haasad arrow brightway2 bw2io bw2data eidl fuzzywuzzy matplotlib-base networkx pandas "pyside2==5.13.*" seaborn
```

Note the missing 'defaults' channel, this is to make sure `seaborn` is picked from the `conda-forge` channel, which in turn means it won't pull in pyqt dependencies (`seaborn` from the `defaults` channel depends on `matplotlib`, which depends on `pyqt`)

**Comment by e4BdSBmUzHowFico5Ktn** [comment] 2019-10-28 16:11
Great to hear! Could you expand slightly on how I install this branch to test it?

**Comment by dgdekoning** [comment] 2019-10-28 16:25
(Just in time, was about to log off :P)

Until this branch is actually merged with the master branch no conda packages will be built.

If you want to to test it please `git clone` the branch:

```
git clone --single-branch --branch refactor-pyside2 https://github.com/dgdekoning/activity-browser.git
```

Which creates a new folder named `activity-browser` with all of the Activity Browser source code and checks out the branch with the pyside2 refactoring.

Then create a conda environment (as mentioned above):

```bash
# Create the environment
conda create -n ab_pyside -y -c conda-forge -c cmutel -c haasad arrow brightway2 bw2io bw2data eidl fuzzywuzzy matplotlib-base networkx pandas "pyside2==5.13.*" seaborn
# Activate the environment
conda activate ab_pyside
```

Then go into the `activity-browser` directory with the terminal and run the `run-activity-browser.py` script to start the activity browser.

```bash
python run-activity-browser.py
```

If all goes well (it passed the linux and macos tests, but not everything is covered) it should open a new window functionally the same as the conda Activity Browser.

**Comment by e4BdSBmUzHowFico5Ktn** [comment] 2019-10-29 15:42
Thanks for the instructions, I can confirm its working on LinuxLite and I will test your branch on the following popular distros:
Debian
Ubuntu newest
Ubuntu LTS
Open Suse
Fedora
Manjaro

I`ll get back with results, I think I`ll find time for this in the next two weeks.

To get back to the original topic;
Would there be any downsides on moving to PySide? I`m personally in favour of more open licensing.

**Comment by dgdekoning** [comment] 2019-11-04 11:05
As an update for everyone interested:

With the upcoming refactoring to PySide2, the Activity Browser will take on the LGPL licence.

If anyone needs to have the Activity Browser under a different licence, please get in touch with @bsteubing and/or me and we'll consider further changes in the future.

**Closed** 2019-11-04 16:39 UTC

**Comment by e4BdSBmUzHowFico5Ktn** [comment] 2020-09-11 07:49
This discussion has been closed for a while but I just ran in to this and I believe this is relevant for any future licensing discussion, so for future reference:
A proper licensing compare page from the European Commission
https://joinup.ec.europa.eu/solution/joinup-licensing-assistant/joinup-licensing-assistant-jla
