### ISSUE TITLE
Certificate verification error when using the sankey diagram

### ISSUE THREAD

**Issue by twoflower42** [LCA-ActivityBrowser/activity-browser#143] opened 2018-04-23 14:41 UTC
I made a fresh installation of Activity-Browser today. When I try to generate a sankey diagram, I get the following error :

```
[15150:15165:0423/162047.509251:ERROR:cert_verify_proc_openssl.cc(212)] X509 Verification error unable to get local issuer certificate : 20 : 2 : 4                                                            
js: Uncaught ReferenceError: d3 is not defined                                                                                                                                                                 
js: Uncaught TypeError: Cannot read property 'format' of undefined
```

I think this might be related to the integrated browser retrieving the d3.js framework online. I am using Fedora 24, with the latest version of MiniConda. I'll try to reproduce on Archlinux tonight.

**Comment by haasad** [comment] 2018-04-23 15:48
I agree that this is most likely caused by retrieving d3 online. I just updated master with a local copy of d3.js to get rid of the step. This also makes the AB work completely offline.

Could you maybe install the [development version](https://github.com/LCA-ActivityBrowser/activity-browser#development-version) and check if this fixes the issue for you?

**Comment by haasad** [comment] 2018-04-24 07:31
Cool, I'll close the issue in the meantime. Please reopen if it still doesn't work. Thanks for your effort!

**Closed by haasad** 2018-04-24 07:31 UTC
Labels: bug
