### ISSUE TITLE
Problem with exporting databases

### ISSUE THREAD

**Issue by gwaeger-00** [LCA-ActivityBrowser/activity-browser#1407] opened 2024-11-15 09:25 UTC
### Updating AB

- [X] Yes, I have [updated AB](https://github.com/LCA-ActivityBrowser/activity-browser#updating-the-ab) and still experience this issue

### What happened?

I tried to export databases via the following button, but there was no file saved at the chosen location. It did not work as BW2Package or Excel, and I also tried some different places to save it. What could be the issue here?
<img width="357" alt="Screenshot 2024-11-15 at 10 09 37" src="https://github.com/user-attachments/assets/21fa2e58-cfad-4579-a69e-338248ee828d">

### Operating system

MacOS

### Conda environment

```shell
(ab) gina@Ginas-MacBook-Pro ~ % conda list
# packages in environment at /Users/gina/anaconda3/envs/ab:
#
# Name                    Version                   Build  Channel
activity-browser          2.10.3             pyhd8ed1ab_1    conda-forge
annotated-types           0.7.0              pyhd8ed1ab_0    conda-forge
appdirs                   1.4.4              pyh9f0ad1d_0    conda-forge
arrow                     1.3.0              pyhd8ed1ab_0    conda-forge
asteval                   1.0.5              pyhd8ed1ab_0    conda-forge
astunparse                1.6.3              pyhd8ed1ab_2    conda-forge
blinker                   1.8.2              pyhd8ed1ab_0    conda-forge
brightway2                2.4.6              pyhd8ed1ab_0    conda-forge
brotli                    1.1.0                h00291cd_2    conda-forge
brotli-bin                1.1.0                h00291cd_2    conda-forge
brotli-python             1.1.0           py311hd89902b_2    conda-forge
brotlicffi                1.1.0.0         py311hd89902b_2    conda-forge
bw2analyzer               0.10               pyhd8ed1ab_0    conda-forge
bw2calc                   1.8.2           py311h6eed73b_0    conda-forge
bw2data                   3.6.6              pyhd8ed1ab_0    conda-forge
bw2io                     0.8.12             pyhd8ed1ab_0    conda-forge
bw2parameters             1.1.0              pyhd8ed1ab_0    conda-forge
bw_migrations             0.2                pyhd8ed1ab_0    conda-forge
bzip2                     1.0.8                hfdf4475_7    conda-forge
ca-certificates           2024.8.30            h8857fd0_0    conda-forge
certifi                   2024.8.30          pyhd8ed1ab_0    conda-forge
cffi                      1.17.1          py311h137bacd_0    conda-forge
charset-normalizer        3.4.0              pyhd8ed1ab_0    conda-forge
click                     8.1.7           unix_pyh707e725_0    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
contourpy                 1.3.0           py311h5ef0cbf_2    conda-forge
cycler                    0.12.1             pyhd8ed1ab_0    conda-forge
dill                      0.3.9              pyhd8ed1ab_0    conda-forge
docopt                    0.6.2                      py_1    conda-forge
ecoinvent_interface       2.4.1              pyhd8ed1ab_0    conda-forge
eight                     1.0.1              pyhd8ed1ab_4    conda-forge
et_xmlfile                2.0.0              pyhd8ed1ab_0    conda-forge
fasteners                 0.17.3             pyhd8ed1ab_0    conda-forge
flask                     3.0.3              pyhd8ed1ab_0    conda-forge
fonttools                 4.54.1          py311h8b4e8a7_1    conda-forge
freetype                  2.12.1               h60636b9_2    conda-forge
future                    1.0.0              pyhd8ed1ab_0    conda-forge
giflib                    5.2.2                h10d778d_0    conda-forge
glib                      2.82.2               hbe7352d_0    conda-forge
glib-tools                2.82.2               h8a9f880_0    conda-forge
gmp                       6.3.0                hf036a51_2    conda-forge
gst-plugins-base          1.24.7               h0ee1d58_0    conda-forge
gstreamer                 1.24.7               h3271b85_0    conda-forge
h2                        4.1.0              pyhd8ed1ab_0    conda-forge
hpack                     4.0.0              pyh9f0ad1d_0    conda-forge
hyperframe                6.0.1              pyhd8ed1ab_0    conda-forge
icu                       75.1                 h120a0e1_0    conda-forge
idna                      3.10               pyhd8ed1ab_0    conda-forge
importlib-metadata        8.5.0              pyha770c72_0    conda-forge
importlib_metadata        8.5.0                hd8ed1ab_0    conda-forge
inflate64                 1.0.0           py311h3336109_2    conda-forge
itsdangerous              2.2.0              pyhd8ed1ab_0    conda-forge
jinja2                    3.1.4              pyhd8ed1ab_0    conda-forge
kiwisolver                1.4.7           py311hf2f7c97_0    conda-forge
krb5                      1.21.3               h37d8d59_0    conda-forge
lcms2                     2.16                 ha2f27b4_0    conda-forge
lerc                      4.0.0                hb486fe8_0    conda-forge
libblas                   3.9.0           25_osx64_openblas    conda-forge
libbrotlicommon           1.1.0                h00291cd_2    conda-forge
libbrotlidec              1.1.0                h00291cd_2    conda-forge
libbrotlienc              1.1.0                h00291cd_2    conda-forge
libcblas                  3.9.0           25_osx64_openblas    conda-forge
libclang-cpp17            17.0.6          default_hb173f14_7    conda-forge
libclang13                19.1.3          default_h0c68bdf_0    conda-forge
libcxx                    19.1.3               hf95d169_0    conda-forge
libdeflate                1.22                 h00291cd_0    conda-forge
libedit                   3.1.20191231         h0678c8f_2    conda-forge
libexpat                  2.6.4                h240833e_0    conda-forge
libffi                    3.4.2                h0d85af4_5    conda-forge
libgfortran               5.0.0           13_2_0_h97931a8_3    conda-forge
libgfortran5              13.2.0               h2873a65_3    conda-forge
libglib                   2.82.2               hb6ef654_0    conda-forge
libhwloc                  2.11.1          default_h456cccd_1000    conda-forge
libiconv                  1.17                 hd75f5a5_2    conda-forge
libintl                   0.22.5               hdfe23c8_3    conda-forge
libintl-devel             0.22.5               hdfe23c8_3    conda-forge
libjpeg-turbo             3.0.0                h0dc2134_1    conda-forge
liblapack                 3.9.0           25_osx64_openblas    conda-forge
libllvm17                 17.0.6               hbedff68_1    conda-forge
libllvm19                 19.1.3               h1e63acb_0    conda-forge
libogg                    1.3.5                hfdf4475_0    conda-forge
libopenblas               0.3.28          openmp_hbf64a52_1    conda-forge
libopus                   1.3.1                hc929b4f_1    conda-forge
libpng                    1.6.44               h4b8f8c9_0    conda-forge
libpq                     16.4                 h365486b_3    conda-forge
libsqlite                 3.47.0               h2f8c449_1    conda-forge
libtiff                   4.7.0                h583c2ba_1    conda-forge
libvorbis                 1.3.7                h046ec9c_0    conda-forge
libwebp                   1.4.0                hc207709_0    conda-forge
libwebp-base              1.4.0                h10d778d_0    conda-forge
libxcb                    1.17.0               hf1f96e2_0    conda-forge
libxml2                   2.13.4               h12808cf_2    conda-forge
libxslt                   1.1.39               h03b04e6_0    conda-forge
libzlib                   1.3.1                hd23fc13_2    conda-forge
llvm-openmp               19.1.3               hf78d878_0    conda-forge
lxml                      4.9.3           py311h719c1e2_3    conda-forge
lxmlh                     1.3.3              pyhd8ed1ab_0    conda-forge
markupsafe                3.0.2           py311h8b4e8a7_0    conda-forge
matplotlib-base           3.9.2           py311h8b21175_1    conda-forge
mkl                       2023.2.0         h54c2260_50500    conda-forge
mrio_common_metadata      0.2.1              pyhd8ed1ab_0    conda-forge
multiprocess              0.70.17         py311h1314207_0    conda-forge
multivolumefile           0.2.3              pyhd8ed1ab_0    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
mysql-common              9.0.1                h918ca22_2    conda-forge
mysql-libs                9.0.1                h502887b_2    conda-forge
ncurses                   6.5                  hf036a51_1    conda-forge
networkx                  3.4.2              pyhd8ed1ab_1    conda-forge
nspr                      4.36                 h97d8b74_0    conda-forge
nss                       3.106                hbde9d96_0    conda-forge
numpy                     1.26.4          py311hc43a94b_0    conda-forge
openjpeg                  2.5.2                h7310d3a_0    conda-forge
openpyxl                  3.1.5           py311h03bb54d_1    conda-forge
openssl                   3.3.2                hd23fc13_0    conda-forge
packaging                 24.1               pyhd8ed1ab_0    conda-forge
pandas                    2.2.3           py311haeb46be_1    conda-forge
pathos                    0.3.3              pyhd8ed1ab_0    conda-forge
patsy                     0.5.6              pyhd8ed1ab_0    conda-forge
pcre2                     10.44                h7634a1b_2    conda-forge
peewee                    3.17.7          py311h59fc955_0    conda-forge
pillow                    11.0.0          py311h1f68098_0    conda-forge
pint                      0.21               pyhd8ed1ab_0    conda-forge
pip                       24.3.1             pyh8b19718_0    conda-forge
platformdirs              4.3.6              pyhd8ed1ab_0    conda-forge
pox                       0.3.5              pyhd8ed1ab_0    conda-forge
ppft                      1.7.6.9            pyhd8ed1ab_0    conda-forge
psutil                    6.1.0           py311h1314207_0    conda-forge
pthread-stubs             0.4               h00291cd_1002    conda-forge
py7zr                     0.22.0             pyhd8ed1ab_0    conda-forge
pybcj                     1.0.2           py311h3336109_1    conda-forge
pycasreg                  0.1.0              pyhd8ed1ab_0    conda-forge
pycparser                 2.22               pyhd8ed1ab_0    conda-forge
pycryptodomex             3.20.0          py311h3336109_1    conda-forge
pydantic                  2.9.2              pyhd8ed1ab_0    conda-forge
pydantic-core             2.23.4          py311h95688db_0    conda-forge
pydantic-settings         2.6.1              pyh3cfb1c2_0    conda-forge
pyecospold                3.5.3              pyhd8ed1ab_0    conda-forge
pyobjc-core               10.3.1          py311hd6939f8_1    conda-forge
pyobjc-framework-cocoa    10.3.1          py311hd6939f8_1    conda-forge
pypardiso                 0.4.6              pyhd8ed1ab_1    conda-forge
pyparsing                 3.2.0              pyhd8ed1ab_1    conda-forge
pyperclip                 1.9.0              pyh534df25_0    conda-forge
pyppmd                    1.1.0           py311hd89902b_1    conda-forge
pyprind                   2.11.2          py311h6eed73b_1006    conda-forge
pyside2                   5.15.15         py311h87dfee4_0    conda-forge
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
python                    3.11.10         ha513fb2_3_cpython    conda-forge
python-dateutil           2.9.0              pyhd8ed1ab_0    conda-forge
python-dotenv             1.0.1              pyhd8ed1ab_0    conda-forge
python-tzdata             2024.2             pyhd8ed1ab_0    conda-forge
python_abi                3.11                    5_cp311    conda-forge
pytz                      2024.1             pyhd8ed1ab_0    conda-forge
pyxlsb                    1.0.10             pyhd8ed1ab_0    conda-forge
pyzstd                    0.16.2          py311hdf6fcd6_0    conda-forge
qhull                     2020.2               h3c5361c_5    conda-forge
qt-main                   5.15.15              h07d6d3d_0    conda-forge
qt-webengine              5.15.15              h46887bd_1    conda-forge
readline                  8.2                  h9e318b2_1    conda-forge
requests                  2.32.3             pyhd8ed1ab_0    conda-forge
salib                     1.5.0              pyhd8ed1ab_0    conda-forge
scipy                     1.14.1          py311hed734c1_1    conda-forge
seaborn                   0.13.2               hd8ed1ab_2    conda-forge
seaborn-base              0.13.2             pyhd8ed1ab_2    conda-forge
setuptools                75.3.0             pyhd8ed1ab_0    conda-forge
setuptools-scm            8.1.0              pyhd8ed1ab_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
stats_arrays              0.7                pyhd8ed1ab_0    conda-forge
statsmodels               0.14.4          py311h0034819_0    conda-forge
tabulate                  0.9.0              pyhd8ed1ab_1    conda-forge
tbb                       2021.13.0            h37c8870_0    conda-forge
texttable                 1.7.0              pyhd8ed1ab_0    conda-forge
tk                        8.6.13               h1abcd95_1    conda-forge
tomli                     2.0.2              pyhd8ed1ab_0    conda-forge
tqdm                      4.67.0             pyhd8ed1ab_0    conda-forge
types-python-dateutil     2.9.0.20241003     pyhff2d567_0    conda-forge
typing-extensions         4.12.2               hd8ed1ab_0    conda-forge
typing_extensions         4.12.2             pyha770c72_0    conda-forge
tzdata                    2024b                hc8b5060_0    conda-forge
unicodecsv                0.14.1             pyhd8ed1ab_2    conda-forge
unicodedata2              15.1.0          py311h1314207_1    conda-forge
unidecode                 1.3.8              pyhd8ed1ab_0    conda-forge
urllib3                   2.2.3              pyhd8ed1ab_0    conda-forge
voluptuous                0.15.2             pyhd8ed1ab_1    conda-forge
werkzeug                  3.1.2              pyhd8ed1ab_0    conda-forge
wheel                     0.44.0             pyhd8ed1ab_0    conda-forge
whoosh                    2.7.4           py311h6eed73b_9    conda-forge
wrapt                     1.16.0          py311h3336109_1    conda-forge
xlrd                      2.0.1              pyhd8ed1ab_3    conda-forge
xlsxwriter                3.2.0              pyhd8ed1ab_0    conda-forge
xorg-libxau               1.0.11               h00291cd_1    conda-forge
xorg-libxdmcp             1.1.5                h00291cd_0    conda-forge
xz                        5.2.6                h775f41a_0    conda-forge
zipfile-deflate64         0.2.0           py311h2725bcf_4    conda-forge
zipp                      3.20.2             pyhd8ed1ab_0    conda-forge
zstandard                 0.23.0          py311hdf6fcd6_1    conda-forge
zstd                      1.5.6                h915ae27_0    conda-forge
```

**Comment by marc-vdm** [comment] 2024-11-15 13:15
I'm closing this as a duplicate of #1372. 
This is being worked on and you will receive a reply in #1372 (for which you should receive an email) once a new version of Activity Browser is released where this issue is solved.

**Closed by marc-vdm** 2024-11-15 13:15 UTC
Labels: bug

**Comment by gwaeger-00** [comment] 2024-11-15 14:22
Thanks for your response.

Is there any possibility to go around this bug?
Because I was only able to use ecoinvent 3.10 in a new project, I would like to somehow transfer databases from previous projects into the new one with the new ecoinvent database.
Do you already have a solution for that?

Kind regards,
Gina Wäger

From: Marc van der Meide ***@***.***>
Date: Friday, 15 November 2024 at 14:15
To: LCA-ActivityBrowser/activity-browser ***@***.***>
Cc: Wäger Gina ***@***.***>, Author ***@***.***>
Subject: Re: [LCA-ActivityBrowser/activity-browser] Problem with exporting databases (Issue #1407)

I'm closing this as a duplicate of #1372<https://github.com/LCA-ActivityBrowser/activity-browser/issues/1372>.
This is being worked on and you will receive a reply in #1372<https://github.com/LCA-ActivityBrowser/activity-browser/issues/1372> (for which you should receive an email) once a new version of Activity Browser is released where this issue is solved.

**Comment by gwaeger-00** [comment] 2024-11-28 07:28
Good morning

Sadly, I did not get an answer yet to the following email.

Were there any new developments made regarding the following issue?

Kind regards,
Gina Wäger

From: Wäger Gina ***@***.***>
Date: Friday, 15 November 2024 at 15:22
To: LCA-ActivityBrowser/activity-browser ***@***.***>, LCA-ActivityBrowser/activity-browser ***@***.***>
Cc: Author ***@***.***>
Subject: Re: [LCA-ActivityBrowser/activity-browser] Problem with exporting databases (Issue #1407)
Thanks for your response.

Is there any possibility to go around this bug?
Because I was only able to use ecoinvent 3.10 in a new project, I would like to somehow transfer databases from previous projects into the new one with the new ecoinvent database.
Do you already have a solution for that?

Kind regards,
Gina Wäger

From: Marc van der Meide ***@***.***>
Date: Friday, 15 November 2024 at 14:15
To: LCA-ActivityBrowser/activity-browser ***@***.***>
Cc: Wäger Gina ***@***.***>, Author ***@***.***>
Subject: Re: [LCA-ActivityBrowser/activity-browser] Problem with exporting databases (Issue #1407)

I'm closing this as a duplicate of #1372<https://github.com/LCA-ActivityBrowser/activity-browser/issues/1372>.
This is being worked on and you will receive a reply in #1372<https://github.com/LCA-ActivityBrowser/activity-browser/issues/1372> (for which you should receive an email) once a new version of Activity Browser is released where this issue is solved.

**Comment by marc-vdm** [comment] 2024-11-28 10:29
Hi Gina,

We have not gotten to this issue yet. Sorry for any inconveniences this is causing. This is an open source project and for a lot of the development, we rely on peoples free time to fix this. I could prioritize your issue, but that would paid, if you would like that, you can email me at marcvandermeide@posteo.net and we can discuss. Otherwise, you will receive an email when this is resolved.
