### ISSUE TITLE
Adding the "default scenario column" changes LCA results considerably

### ISSUE THREAD

**Issue by CHarpprecht** [LCA-ActivityBrowser/activity-browser#592] opened 2021-04-27 17:07 UTC
Hi there,

if I run the same LCA setups with the same scenario parameters I get different results depending on whether the default column has been added or not. The results differ for the default values and all scenarios. The difference is not negligible, see screenshots: 
![grafik](https://user-images.githubusercontent.com/47253039/116282821-85157200-a78b-11eb-99b7-c4fa345e68db.png)
![grafik](https://user-images.githubusercontent.com/47253039/116283051-c1e16900-a78b-11eb-9c1b-77fa38f89ddc.png)

I think that the results without the default columns are wrong, since in my older AB development version, which does not have this feature of the default column yet, I get the same results as for the newer AB version with the default column. 
Plus, the results for "default" are the same as for a standard LCA without any scenarios. 

This happened in the newest AB development version (2021.04.21) but also in an older one from 2021.04.06.

**Comment by ugjav** [comment] 2021-09-24 08:39
Hi all, 

I face a similar issue regarding scenario-based LCA, detailed below:

I compare a non-parameterized reference flow with the exact same reference flow but parameterized (i.e. parameters are chosen in order that the same reference flow values appear for both). 

Accordingly, running a standard LCA, i have the same results for both parameterized and non-parameterized scenario:
![image](https://user-images.githubusercontent.com/91123920/134643868-661ef1c6-9e09-4ce8-8674-47fa69d199e4.png)

However, if i run a scenario-based LCA (only one scenario with default values as in standard LCA), I achieve different results between the parameterized and non-parameterized reference flows!
![image](https://user-images.githubusercontent.com/91123920/134644071-349bce9c-c835-4eed-88a6-6c853f7708d4.png)

No matter which order or name I give to the scenario, i still have this difference that should not exist, and I do not know which result to chose!
Thank you for reconsidering this issue,
Wish you all a good week-end!

**Comment by ljlazar** [comment] 2022-02-15 15:31
Hi @ugjav,
I had the same issue occuring once in a while and I was not able to identify the cause yet. However, in my case it is usually fixable by duplicating the affected activity. If you run a scenario LCA with the duplicated activity the results will be the same compared to the standard LCA. Hope this helps a bit!

**Comment by CHarpprecht** [comment] 2022-03-21 20:29
@bsteubing : 
I think that the results without the default columns are wrong, since in my older AB development version, which does not have this feature of the default column yet, I get the same results as for the newer AB version with the default column.
Plus, the results for "default" are the same as for a standard LCA without any scenarios. (this is just a quote from the initial issue, I have not looked into it again)

**Comment by marc-vdm** [comment] 2023-09-14 14:27
Closing this as resolved in #1025

**Closed by marc-vdm** 2023-09-14 14:27 UTC
Labels: bug
