### ISSUE TITLE
GUI: Inventory table reordered by string not float

### ISSUE THREAD

**Issue by Athunc** [LCA-ActivityBrowser/activity-browser#231] opened 2019-04-09 11:25 UTC
A minor issue: In the MLCA results Inventory Table, reordering the table by the content of a column which contains only numbers, orders them as strings, meaning by alphabetnumerical sequence rather than quantity.

**Comment by dgdekoning** [comment] 2019-07-26 09:14
I don't think this is the case.

When sorting by one of the functional units it sorts the entire table by that column, if there are other functional units their ordering is also altered to reflect the changed rows caused by the sort.

Can you give an example of the ordering being done incorrectly?

**Comment by nheeren** [comment] 2019-08-08 11:13
I think this example / screenshot illustrates the issue nicely. Numbers are not sorted correctly. Numbers with scientific notation come before the ones with decimals. 

![Screenshot 2019-08-08 at 13 12 09](https://user-images.githubusercontent.com/5136954/62698736-2a981900-b9de-11e9-9ee4-38bf99d8d303.png)

**Comment by dgdekoning** [comment] 2019-08-08 11:33
Thanks! It looks like this is one of the tables from the activity tab, right?

**Comment by nheeren** [comment] 2019-08-08 11:49
Yes, but i think it also occurs in other tables.

**Comment by dgdekoning** [comment] 2019-08-08 12:07
I wonder if this has to do with the differences between the implementations of the ABTableWidget (QTableWidget) class and the (renamed since yesterday) ABDataFrameView (QTableView) class.
Switching over to a single implementation for all tables is something @bsteubing has been wanting to do for a while.

Looking a bit deeper I think the sorting issue is caused by [formatting the amounts as a string](https://github.com/LCA-ActivityBrowser/activity-browser/blob/8c7a0e956cea8dafbc6d5fae48d846d7dd530212/activity_browser/app/ui/tables/activity.py#L169), at least for `ExchangeTable` tables. Which does indeed mess up sorting.

**Comment by dgdekoning** [comment] 2019-08-27 07:57
With all of the tables refactored to use view classes (which will actually show values as floats, booleans, strings, integers) I think this issue is now resolved. Will close it when the new stable version is released.

**Comment by dgdekoning** [comment] 2019-08-27 10:17
Fixed in 2.3.3

Please give me a heads-up if this occurs again.

**Closed by dgdekoning** 2019-08-27 10:17 UTC

**Comment by nheeren** [comment] 2019-09-19 21:27
Similar issue, different place. I noticed in the 'LCA results' > 'Process Contributions' table, when I click on the LCIA score for sorting and _after that_ change the cut-off, the order will get messed up. Not a big deal, but I thought I'll mention it...

![Screenshot 2019-09-19 at 23 21 16](https://user-images.githubusercontent.com/5136954/65282309-e9df0400-db34-11e9-9207-b0a28459e9e8.png)

**Comment by dgdekoning** [comment] 2019-09-20 13:37
The issue now isn't so much that the order is being messed up but that the sorting isn't being re-applied when the table is changed.

Altering the cut-off causes AB to completely rebuild the underlying DataFrame (ordering it by index by default as you see in the image).

I'm thinking that the relevant model or the view class can be improved by checking if sorting has been performed before it rebuilds the table and then applying the correct sorting afterwards.
